# Database: Northwind
#
# Purpose:
# Calculate the total revenue generated by each product using pandas.
#
# Revenue is calculated as:
# Revenue = Unit Price × Quantity Sold
#
# Concepts practiced:
# - sqlite3
# - pandas.read_sql_query()
# - DataFrame column selection
# - merge()
# - Calculated columns
# - groupby()
# - sort_values()
# - to_csv()


import sqlite3
import pandas as pd
from pathlib import Path

# Database path relative to the project root.
DB_PATH = Path(__file__).resolve().parents[2] / 'database' / 'northwind.db'


with sqlite3.connect(DB_PATH) as nw:
    
    query_od = '''
        SELECT *
        FROM Orderdetails
    '''
    order_details = pd.read_sql_query(query_od, nw)
    
    query_p = '''
        SELECT *
        FROM Products
    '''
    products = pd.read_sql_query(query_p, nw)


# Combine product information with order details using ProductID.
revenue_by_products = products[
    ['ProductID','ProductName','Price']
    ].merge(
        order_details[['ProductID', 'Quantity']],
        on = 'ProductID'
        )

# Calculate the revenue generated by each order detail.
revenue_by_products['Revenue'] = (
    revenue_by_products['Price'] * revenue_by_products['Quantity']
    )

# Aggregate revenue by product and sort from highest to lowest.
revenue_by_products = (
    revenue_by_products
    .groupby(['ProductID', 'ProductName'], as_index = False)['Revenue']
    .sum()
    .sort_values('Revenue', ascending = False)
)

print(revenue_by_products)

# Creating a file to export the results as a csv file.
FILE_PATH = Path(__file__).resolve().parents[1] / 'reports' / 'revenue_by_products.csv'
revenue_by_products.to_csv(FILE_PATH, index = False)