# Database: Northwind
#
# Purpose:
# Calculate the total revenue generated by each product category using pandas.
#
# Revenue is calculated as:
# Revenue = Unit Price × Quantity Sold
#
# Concepts practiced:
# - sqlite3
# - pandas.read_sql_query()
# - DataFrame column selection
# - merge()
# - Calculated columns
# - groupby()
# - sort_values()
# - to_csv()


import sqlite3
import pandas as pd
from pathlib import Path

# Database path relative to the project root.
DB_PATH = Path(__file__).resolve().parents[2] / 'database' / 'northwind.db'

with sqlite3.connect(DB_PATH) as nw:
    
    query_od = '''
        SELECT ProductID,
               Quantity 
        FROM OrderDetails
    '''
    order_details = pd.read_sql_query(query_od, nw)
    
    query_p = '''
        SELECT ProductID,
               CategoryID,
               Price 
        FROM Products
    '''
    products = pd.read_sql_query(query_p, nw)
    
    query_cat = '''
        SELECT CategoryID,
               CategoryName 
        FROM Categories
    '''
    categories = pd.read_sql_query(query_cat, nw)

# Combine category information with products using CategoryID 
# and order details with ProductID.    
revenue_by_category = (
    categories
    .merge(products, on = 'CategoryID')
    .merge(order_details, on = 'ProductID')
)

# Calculate the revenue generated by each order detail.
revenue_by_category['Revenue'] = (
    revenue_by_category['Price'] * revenue_by_category['Quantity']
)

# Aggregate revenue by product and sort from highest to lowest.
revenue_by_category = (
    revenue_by_category
    .groupby(['CategoryID', 'CategoryName'], as_index = False)['Revenue']
    .sum()
    .sort_values('Revenue', ascending = False)
)

print(revenue_by_category)

# Creating a file to export the results as a csv file.
FILE_PATH = Path(__file__).resolve().parents[1] / 'reports' / 'revenue_by_category.csv'
revenue_by_category.to_csv(FILE_PATH, index = False)